### ISSUE TITLE
Sync action not triggering on: push workflow

### ISSUE THREAD

**Issue by mwittrock** [engswee/flashpipe-action#4]
Hi Eng Swee

It seems to me that the sync action is not triggering an "on: push" workflow in the same repo. I'm using the sync action to synchronize a single iflow from the tenant to git. This works perfectly and the iflow is committed as expected. However, another workflow, defined to trigger on a push to the repo, is not run subsequently.

The workflow looks like this:

```
name: Sync my iflow

on:
  workflow_dispatch

jobs:
  sync:
    runs-on: ubuntu-latest
    container:
      image: engswee/flashpipe:latest

    steps:
    - uses: actions/checkout@v4

    - name: 'Sync my iflow'
      uses: engswee/flashpipe-action/sync@v1
      with:
        tmn-host: ${{ vars.API_ENDPOINT_HOST }}
        oauth-host: ${{ vars.OAUTH_HOST }}
        oauth-clientid: ${{ secrets.CLIENT_ID }}
        oauth-clientsecret: ${{ secrets.CLIENT_SECRET }}
        package-id: MyPackageID
        ids-include: MyIflowID
        draft-handling: SKIP
        git-commit-msg: Synced my iflow to repo with FlashPipe
        target: git
```

Here is a sample workflow, that is not triggered:

```
name: Sample on push workflow

on:
  push

jobs:
  sample:
    runs-on: ubuntu-latest

    steps:
      - run: echo "Pipeline was activated"
```

Is my understanding wrong?

Thank you and regards,

Morten
